name: Generate Svgo

on:
  workflow_dispatch: {}
  schedule:
    # Runs at 00:00 UTC on Sun
    - cron: '0 0 * * 0'

  push:
    # Also trigger CI when commit pushed to ci branch to dev the workflow script
    branches:
      - ci

jobs:
  generate-svgo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: "Clone Master"

      - name: "Install svgo"
        run: sudo npm install -g svgo

      - uses: actions/checkout@v2
        name: "Download MaterialDesignIcons"
        with:
          repository: Templarian/MaterialDesign
          path: mdi

      - name: "Compress svgs"
        run: |
          rm -rf svg
          mkdir svg
          cd mdi/svg
          for f in *.svg ; do svgo --config $GITHUB_WORKSPACE/svgo.config.js -q -i "$f" -o $GITHUB_WORKSPACE/svg/"$f" ; done

      - name: "Deploy"
        run: |
          cd mdi
          MDI_SHA_1=$(git rev-parse HEAD)
          cd ..
          git add svg/*
          git -c user.name='ci' -c user.email='ci' commit -m "⬆️ Update to $MDI_SHA_1"
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:master
        # Make sure that the job doesn't fail if no changed hapenned
        continue-on-error: true
